export default function() {
  return [
    ['no-break space', ' '],
    ['soft hyphen', '­'],
    ['quotation mark', '"'],
    ['cent sign', '¢'],
    ['euro sign', '€'],
    ['pound sign', '£'],
    ['yen sign', '¥'],
    ['copyright sign', '©'],
    ['registered sign', '®'],
    ['trade mark sign', '™'],
    ['per mille sign', '‰'],
    ['micro sign', 'µ'],
    ['middle dot', '·'],
    ['bullet', '•'],
    ['three dot leader', '…'],
    ['minutes / feet', '′'],
    ['seconds / inches', '″'],
    ['section sign', '§'],
    ['paragraph sign', '¶'],
    ['sharp s / ess-zed', 'ß'],
    ['single left-pointing angle quotation mark', '‹'],
    ['single right-pointing angle quotation mark', '›'],
    ['left pointing guillemet', '«'],
    ['right pointing guillemet', '»'],
    ['left single quotation mark', '‘'],
    ['right single quotation mark', '’'],
    ['left double quotation mark', '“'],
    ['right double quotation mark', '”'],
    ['single low-9 quotation mark', '‚'],
    ['double low-9 quotation mark', '„'],
    ['less-than sign', '<'],
    ['greater-than sign', '>'],
    ['less-than or equal to', '≤'],
    ['greater-than or equal to', '≥'],
    ['en dash', '–'],
    ['em dash', '—'],
    ['macron', '¯'],
    ['overline', '‾'],
    ['currency sign', '¤'],
    ['broken bar', '¦'],
    ['diaeresis', '¨'],
    ['inverted exclamation mark', '¡'],
    ['turned question mark', '¿'],
    ['circumflex accent', 'ˆ'],
    ['small tilde', '˜'],
    ['degree sign', '°'],
    ['minus sign', '−'],
    ['plus-minus sign', '±'],
    ['division sign', '÷'],
    ['fraction slash', '⁄'],
    ['multiplication sign', '×'],
    ['superscript one', '¹'],
    ['superscript two', '²'],
    ['superscript three', '³'],
    ['fraction one quarter', '¼'],
    ['fraction one half', '½'],
    ['fraction three quarters', '¾'],
    ['function / florin', 'ƒ'],
    ['integral', '∫'],
    ['n-ary sumation', '∑'],
    ['infinity', '∞'],
    ['square root', '√'],
    ['similar to', '∼'],
    ['approximately equal to', '≅'],
    ['almost equal to', '≈'],
    ['not equal to', '≠'],
    ['identical to', '≡'],
    ['element of', '∈'],
    ['not an element of', '∉'],
    ['contains as member', '∋'],
    ['n-ary product', '∏'],
    ['logical and', '∧'],
    ['logical or', '∨'],
    ['not sign', '¬'],
    ['intersection', '∩'],
    ['union', '∪'],
    ['partial differential', '∂'],
    ['for all', '∀'],
    ['there exists', '∃'],
    ['diameter', '∅'],
    ['backward difference', '∇'],
    ['asterisk operator', '∗'],
    ['proportional to', '∝'],
    ['angle', '∠'],
    ['acute accent', '´'],
    ['cedilla', '¸'],
    ['feminine ordinal indicator', 'ª'],
    ['masculine ordinal indicator', 'º'],
    ['dagger', '†'],
    ['double dagger', '‡'],
    ['A - grave', 'À'],
    ['A - acute', 'Á'],
    ['A - circumflex', 'Â'],
    ['A - tilde', 'Ã'],
    ['A - diaeresis', 'Ä'],
    ['A - ring above', 'Å'],
    ['A - macron', 'Ā'],
    ['ligature AE', 'Æ'],
    ['C - cedilla', 'Ç'],
    ['E - grave', 'È'],
    ['E - acute', 'É'],
    ['E - circumflex', 'Ê'],
    ['E - diaeresis', 'Ë'],
    ['E - macron', 'Ē'],
    ['I - grave', 'Ì'],
    ['I - acute', 'Í'],
    ['I - circumflex', 'Î'],
    ['I - diaeresis', 'Ï'],
    ['I - macron', 'Ī'],
    ['ETH', 'Ð'],
    ['N - tilde', 'Ñ'],
    ['O - grave', 'Ò'],
    ['O - acute', 'Ó'],
    ['O - circumflex', 'Ô'],
    ['O - tilde', 'Õ'],
    ['O - diaeresis', 'Ö'],
    ['O - slash', 'Ø'],
    ['O - macron', 'Ō'],
    ['ligature OE', 'Œ'],
    ['S - caron', 'Š'],
    ['U - grave', 'Ù'],
    ['U - acute', 'Ú'],
    ['U - circumflex', 'Û'],
    ['U - diaeresis', 'Ü'],
    ['U - macron', 'Ū'],
    ['Y - acute', 'Ý'],
    ['Y - diaeresis', 'Ÿ'],
    ['Y - macron', 'Ȳ'],
    ['THORN', 'Þ'],
    ['a - grave', 'à'],
    ['a - acute', 'á'],
    ['a - circumflex', 'â'],
    ['a - tilde', 'ã'],
    ['a - diaeresis', 'ä'],
    ['a - ring above', 'å'],
    ['a - macron', 'ā'],
    ['ligature ae', 'æ'],
    ['c - cedilla', 'ç'],
    ['e - grave', 'è'],
    ['e - acute', 'é'],
    ['e - circumflex', 'ê'],
    ['e - diaeresis', 'ë'],
    ['e - macron', 'ē'],
    ['i - grave', 'ì'],
    ['i - acute', 'í'],
    ['i - circumflex', 'î'],
    ['i - diaeresis', 'ï'],
    ['i - macron', 'ī'],
    ['eth', 'ð'],
    ['n - tilde', 'ñ'],
    ['o - grave', 'ò'],
    ['o - acute', 'ó'],
    ['o - circumflex', 'ô'],
    ['o - tilde', 'õ'],
    ['o - diaeresis', 'ö'],
    ['o slash', 'ø'],
    ['o macron', 'ō'],
    ['ligature oe', 'œ'],
    ['s - caron', 'š'],
    ['u - grave', 'ù'],
    ['u - acute', 'ú'],
    ['u - circumflex', 'û'],
    ['u - diaeresis', 'ü'],
    ['u - macron', 'ū'],
    ['y - acute', 'ý'],
    ['thorn', 'þ'],
    ['y - diaeresis', 'ÿ'],
    ['y - macron', 'ȳ'],
    ['Alpha', 'Α'],
    ['Beta', 'Β'],
    ['Gamma', 'Γ'],
    ['Delta', 'Δ'],
    ['Epsilon', 'Ε'],
    ['Zeta', 'Ζ'],
    ['Eta', 'Η'],
    ['Theta', 'Θ'],
    ['Iota', 'Ι'],
    ['Kappa', 'Κ'],
    ['Lambda', 'Λ'],
    ['Mu', 'Μ'],
    ['Nu', 'Ν'],
    ['Xi', 'Ξ'],
    ['Omicron', 'Ο'],
    ['Pi', 'Π'],
    ['Rho', 'Ρ'],
    ['Sigma', 'Σ'],
    ['Tau', 'Τ'],
    ['Upsilon', 'Υ'],
    ['Phi', 'Φ'],
    ['Chi', 'Χ'],
    ['Psi', 'Ψ'],
    ['Omega', 'Ω'],
    ['alpha', 'α'],
    ['beta', 'β'],
    ['gamma', 'γ'],
    ['delta', 'δ'],
    ['epsilon', 'ε'],
    ['zeta', 'ζ'],
    ['eta', 'η'],
    ['theta', 'θ'],
    ['iota', 'ι'],
    ['kappa', 'κ'],
    ['lambda', 'λ'],
    ['mu', 'μ'],
    ['nu', 'ν'],
    ['xi', 'ξ'],
    ['omicron', 'ο'],
    ['pi', 'π'],
    ['rho', 'ρ'],
    ['final sigma', 'ς'],
    ['sigma', 'σ'],
    ['tau', 'τ'],
    ['upsilon', 'υ'],
    ['phi', 'φ'],
    ['chi', 'χ'],
    ['psi', 'ψ'],
    ['omega', 'ω'],
    ['alef symbol', 'ℵ'],
    ['pi symbol', 'ϖ'],
    ['real part symbol', 'ℜ'],
    ['upsilon - hook symbol', 'ϒ'],
    ['Weierstrass p', '℘'],
    ['imaginary part', 'ℑ'],
    ['leftwards arrow', '←'],
    ['upwards arrow', '↑'],
    ['rightwards arrow', '→'],
    ['downwards arrow', '↓'],
    ['left right arrow', '↔'],
    ['carriage return', '↵'],
    ['leftwards double arrow', '⇐'],
    ['upwards double arrow', '⇑'],
    ['rightwards double arrow', '⇒'],
    ['downwards double arrow', '⇓'],
    ['left right double arrow', '⇔'],
    ['therefore', '∴'],
    ['subset of', '⊂'],
    ['superset of', '⊃'],
    ['not a subset of', '⊄'],
    ['subset of or equal to', '⊆'],
    ['superset of or equal to', '⊇'],
    ['circled plus', '⊕'],
    ['circled times', '⊗'],
    ['perpendicular', '⊥'],
    ['dot operator', '⋅'],
    ['left ceiling', '⌈'],
    ['right ceiling', '⌉'],
    ['left floor', '⌊'],
    ['right floor', '⌋'],
    ['left-pointing angle bracket', '〈'],
    ['right-pointing angle bracket', '〉'],
    ['lozenge', '◊'],
    ['black spade suit', '♠'],
    ['black club suit', '♣'],
    ['black heart suit', '♥'],
    ['black diamond suit', '♦'],
    ['en space', ' '],
    ['em space', ' '],
    ['thin space', ' '],
    ['zero width non-joiner', '‌'],
    ['zero width joiner', '‍'],
    ['left-to-right mark', '‎'],
    ['right-to-left mark', '‏']
  ]
}
